// Auto-generated by generate_data.py — DO NOT EDIT
const DASHBOARD_DATA = {
  "kpi": {
    "underway": 5,
    "moored": 0,
    "total_ton": "350,000",
    "avg_speed_kn": 12.2,
    "wind_kn": 9.3,
    "wave_m": 1.06,
    "safety": "SAFE",
    "updated": "2026-02-19 10:47 UTC"
  },
  "vessels": [
    {
      "id": "SH-001",
      "name": "SUNRISE JEONBUK",
      "imo": "9800005",
      "lon": 124.96824,
      "lat": 34.66815,
      "speed_kn": 12.8,
      "course_deg": 48.6,
      "progress": 72.0,
      "dist_nm": 106.5,
      "eta": "02/19 19:08",
      "cargo": "석탄",
      "qty_ton": 68000,
      "dwt": 75000,
      "origin": "상하이항",
      "dest": "새만금항",
      "origin_code": "CNSHA",
      "dest_code": "KRSMG",
      "status": "항해중",
      "trail": [
        [
          124.21453,
          33.52421
        ],
        [
          124.44876,
          33.91459
        ],
        [
          124.68299,
          34.30498
        ],
        [
          124.80015,
          34.50015
        ],
        [
          124.88441,
          34.58441
        ],
        [
          124.96824,
          34.66815
        ]
      ],
      "route_color": [
        0,
        140,
        255
      ]
    },
    {
      "id": "SH-002",
      "name": "WEST SEA PRIDE",
      "imo": "9800007",
      "lon": 123.45627,
      "lat": 36.8672,
      "speed_kn": 12.8,
      "course_deg": 111.3,
      "progress": 45.0,
      "dist_nm": 164.7,
      "eta": "02/19 23:42",
      "cargo": "철광석",
      "qty_ton": 79000,
      "dwt": 82000,
      "origin": "다롄항",
      "dest": "새만금항",
      "origin_code": "CNDLC",
      "dest_code": "KRSMG",
      "status": "항해중",
      "trail": [
        [
          122.56951,
          38.10269
        ],
        [
          122.86517,
          37.68876
        ],
        [
          123.16047,
          37.27535
        ],
        [
          123.30796,
          37.06886
        ],
        [
          123.38171,
          36.96561
        ],
        [
          123.45627,
          36.8672
        ]
      ],
      "route_color": [
        0,
        200,
        180
      ]
    },
    {
      "id": "SH-003",
      "name": "YELLOW SEA GIANT",
      "imo": "9800010",
      "lon": 125.95776,
      "lat": 35.98615,
      "speed_kn": 11.7,
      "course_deg": 90.2,
      "progress": 88.0,
      "dist_nm": 36.8,
      "eta": "02/19 13:57",
      "cargo": "곡물",
      "qty_ton": 88000,
      "dwt": 95000,
      "origin": "칭다오항",
      "dest": "군산항",
      "origin_code": "CNQDG",
      "dest_code": "KRGUN",
      "status": "항해중",
      "trail": [
        [
          124.51195,
          36.0
        ],
        [
          124.99367,
          36.0
        ],
        [
          125.47539,
          36.0
        ],
        [
          125.71609,
          35.99383
        ],
        [
          125.83643,
          35.99039
        ],
        [
          125.95776,
          35.98615
        ]
      ],
      "route_color": [
        80,
        220,
        120
      ]
    },
    {
      "id": "SH-004",
      "name": "SAEMANGEUM STAR",
      "imo": "9800008",
      "lon": 123.22268,
      "lat": 31.54504,
      "speed_kn": 11.3,
      "course_deg": 32.4,
      "progress": 30.0,
      "dist_nm": 307.9,
      "eta": "02/20 13:59",
      "cargo": "알루미나",
      "qty_ton": 54000,
      "dwt": 58000,
      "origin": "닝보항",
      "dest": "새만금항",
      "origin_code": "CNNBO",
      "dest_code": "KRSMG",
      "status": "항해중",
      "trail": [
        [
          122.53147,
          30.54496
        ],
        [
          122.76391,
          30.87701
        ],
        [
          122.99634,
          31.20906
        ],
        [
          123.11256,
          31.37508
        ],
        [
          123.17067,
          31.4581
        ],
        [
          123.22268,
          31.54504
        ]
      ],
      "route_color": [
        255,
        180,
        0
      ]
    },
    {
      "id": "SH-005",
      "name": "NEW JEONBUK",
      "imo": "9800012",
      "lon": 119.1014,
      "lat": 38.46719,
      "speed_kn": 12.4,
      "course_deg": 111.5,
      "progress": 15.0,
      "dist_nm": 392.5,
      "eta": "02/20 18:20",
      "cargo": "유연탄",
      "qty_ton": 61000,
      "dwt": 65000,
      "origin": "톈진항",
      "dest": "새만금항",
      "origin_code": "CNTXG",
      "dest_code": "KRSMG",
      "status": "항해중",
      "trail": [
        [
          117.72,
          39.0
        ],
        [
          118.11349,
          38.84629
        ],
        [
          118.60537,
          38.65415
        ],
        [
          118.85131,
          38.55808
        ],
        [
          118.97428,
          38.51005
        ],
        [
          119.1014,
          38.46719
        ]
      ],
      "route_color": [
        255,
        80,
        80
      ]
    }
  ],
  "routes": [
    {
      "id": "R01",
      "src_lon": 121.474,
      "src_lat": 31.23,
      "dst_lon": 126.61,
      "dst_lat": 35.83,
      "origin": "상하이항",
      "dest": "새만금항",
      "color": [
        0,
        140,
        255
      ]
    },
    {
      "id": "R02",
      "src_lon": 121.615,
      "src_lat": 38.914,
      "dst_lon": 126.61,
      "dst_lat": 35.83,
      "origin": "다롄항",
      "dest": "새만금항",
      "color": [
        0,
        200,
        180
      ]
    },
    {
      "id": "R03",
      "src_lon": 120.383,
      "src_lat": 36.067,
      "dst_lon": 126.716,
      "dst_lat": 35.982,
      "origin": "칭다오항",
      "dest": "군산항",
      "color": [
        80,
        220,
        120
      ]
    },
    {
      "id": "R04",
      "src_lon": 121.544,
      "src_lat": 29.868,
      "dst_lon": 126.61,
      "dst_lat": 35.83,
      "origin": "닝보항",
      "dest": "새만금항",
      "color": [
        255,
        180,
        0
      ]
    },
    {
      "id": "R05",
      "src_lon": 117.715,
      "src_lat": 39.004,
      "dst_lon": 126.61,
      "dst_lat": 35.83,
      "origin": "톈진항",
      "dest": "새만금항",
      "color": [
        255,
        80,
        80
      ]
    }
  ],
  "ports": [
    {
      "code": "KRSMG",
      "name": "새만금항",
      "lon": 126.61,
      "lat": 35.83,
      "country": "KR",
      "is_dest": true
    },
    {
      "code": "KRGUN",
      "name": "군산항",
      "lon": 126.716,
      "lat": 35.982,
      "country": "KR",
      "is_dest": true
    },
    {
      "code": "CNSHA",
      "name": "상하이항",
      "lon": 121.474,
      "lat": 31.23,
      "country": "CN",
      "is_dest": false
    },
    {
      "code": "CNDLC",
      "name": "다롄항",
      "lon": 121.615,
      "lat": 38.914,
      "country": "CN",
      "is_dest": false
    },
    {
      "code": "CNQDG",
      "name": "칭다오항",
      "lon": 120.383,
      "lat": 36.067,
      "country": "CN",
      "is_dest": false
    },
    {
      "code": "CNNBO",
      "name": "닝보항",
      "lon": 121.544,
      "lat": 29.868,
      "country": "CN",
      "is_dest": false
    },
    {
      "code": "CNTXG",
      "name": "톈진항",
      "lon": 117.715,
      "lat": 39.004,
      "country": "CN",
      "is_dest": false
    }
  ],
  "weather": {
    "points": [
      {
        "id": "WP-01",
        "name": "군산 서방",
        "lon": 125.5,
        "lat": 35.8,
        "wind_kn": 9.1,
        "wind_dir": 290.3,
        "wave_m": 1.02,
        "current_kn": 0.3,
        "water_temp": 9.0,
        "visibility": 20,
        "safety": "SAFE"
      },
      {
        "id": "WP-02",
        "name": "새만금 인근",
        "lon": 126.0,
        "lat": 35.83,
        "wind_kn": 8.6,
        "wind_dir": 337.9,
        "wave_m": 0.97,
        "current_kn": 0.52,
        "water_temp": 6.7,
        "visibility": 5,
        "safety": "SAFE"
      },
      {
        "id": "WP-03",
        "name": "서해 중부",
        "lon": 124.0,
        "lat": 34.5,
        "wind_kn": 9.1,
        "wind_dir": 292.2,
        "wave_m": 1.1,
        "current_kn": 0.33,
        "water_temp": 7.3,
        "visibility": 5,
        "safety": "SAFE"
      },
      {
        "id": "WP-04",
        "name": "서해 북부",
        "lon": 123.5,
        "lat": 37.0,
        "wind_kn": 11.8,
        "wind_dir": 317.6,
        "wave_m": 1.32,
        "current_kn": 0.38,
        "water_temp": 9.1,
        "visibility": 15,
        "safety": "SAFE"
      },
      {
        "id": "WP-05",
        "name": "군산항 입구",
        "lon": 126.5,
        "lat": 35.95,
        "wind_kn": 7.7,
        "wind_dir": 304.5,
        "wave_m": 0.87,
        "current_kn": 0.56,
        "water_temp": 5.4,
        "visibility": 10,
        "safety": "SAFE"
      }
    ],
    "summary": {
      "avg_wind_kn": 9.3,
      "avg_wave_m": 1.06,
      "avg_current_kn": 0.42,
      "overall_safety": "SAFE"
    }
  }
};
